export const getLabel = {
  characters: 'Carácter del procedimiento',
  form: 'Forma del procedimiento',
  state: 'Estado',
  template: 'Plantilla',
  type: 'Tipo de contratación',
};

export const getGroupLabel = {
  govOrder: 'Orden de gobierno',
  template: 'Plantilla del expediente',
  legal: 'Fundamento legal',
  character: 'Carácter del procedimiento',
  contractType: 'Tipo de contratación',
  processType: 'Tipo de procedimiento',
  formParticipation: 'Forma de participación',
  contractCurrency: 'Moneda del contrato',
  contractEstatus: 'Estatus del contrato',
  contractMarco: 'Contrato marco',
  modifyConvenio: 'Convenio modificatorio',
  purchaseCompleted: 'Compra consolidada',
  contractPluriannual: 'Contrato plurianual',
  companySize: 'Estratificación de la empresa',
  companyCountryKey: 'Clave del país de la empresa',
  rfcVerified: 'RFC verificado en el SAT',
};

export const getLabelSingleFilter = {
  instAcronym: 'Siglas de la Institución',
  inst: 'Institución',
  keyUC: 'Clave de la UC',
  nameUC: 'Nombre de la UC',
  managerUC: 'Responsable de la UC',
  expCode: 'Código del expediente',
  expRef: 'Referencia del expediente',
  keyCUCOP: 'Clave CUCOP',
  expTitle: 'Título del expediente',
  processNum: 'Número del procedimiento',
  falloDate: 'Fecha de fallo',
  publishDate: 'Fecha de publicación',
  openDate: 'Fecha de apertura',
  processType: 'Tipo de procedimiento',
  contractCode: 'Tipo de contratación',
  contractControlNum: 'Código del contrato',
  contractTitle: 'Título del contrato',
  contractDesc: 'Descripción del contrato',
  contractStartDate: 'Fecha de inicio del contrato',
  contractEndDate: 'Fecha de fin del contrato',
  contractAmount: 'Importe del contrato',
  keyProgramFederal: 'Clave del programa federal',
  contractSignDate: 'Fecha de firma del contrato',
  keyWalletSHCP: 'Clave de cartera SHCP',
  folioRUPC: 'Folio en el RUPC',
  rfc: 'RFC',
  providerName: 'Proveedor o contratista',
  externCredit: 'Crédito externo',
  financialOrganization: 'Organismo financiero',
};
