export const visibilityModel = {
  govOrder: false,
  inst: false,
  keyUC: false,
  managerUC: false,
  keyCUCOP: false,
  processNum: false,
  keyCOG: false,
  contractCode: false,
  contractControlNum: false,
  modifyConvenio: false,
  keyProgramFederal: false,
  purchaseCompleted: false,
  folioRUPC: false,
  rfcVerified: false,
  financialOrganization: false,
  expCode: false,
  falloDate: false,
  publishDate: false,
  openDate: false,
  formParticipation: false,
  contractStartDate: false,
  contractEndDate: false,
  externCredit: false,
};
